[package]
name = "atcoder"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "abc460_a"
path = "abc460/a.rs"

[[bin]]
name = "abc460_b"
path = "abc460/b.rs"

[[bin]]
name = "abc460_c"
path = "abc460/c.rs"

[[bin]]
name = "abc460_d"
path = "abc460/d.rs"

[[bin]]
name = "abc460_e"
path = "abc460/e.rs"

[[bin]]
name = "abc460_f"
path = "abc460/f.rs"

[[bin]]
name = "practice2a"
path = "practice2/a.rs"

[[bin]]
name = "abc461_a"
path = "abc461/a.rs"

[[bin]]
name = "abc461_b"
path = "abc461/b.rs"

[[bin]]
name = "abc461_c"
path = "abc461/c.rs"

[[bin]]
name = "abc461_d"
path = "abc461/d.rs"

[[bin]]
name = "abc461_e"
path = "abc461/e.rs"

[[bin]]
name = "abc461_f"
path = "abc461/f.rs"

[[bin]]
name = "abc463_a"
path = "abc463/a.rs"

[[bin]]
name = "abc463_b"
path = "abc463/b.rs"

[[bin]]
name = "abc463_c"
path = "abc463/c.rs"

[[bin]]
name = "abc463_d"
path = "abc463/d.rs"

[[bin]]
name = "abc463_e"
path = "abc463/e.rs"

[[bin]]
name = "abc465_a"
path = "abc465/a.rs"

[[bin]]
name = "abc465_b"
path = "abc465/b.rs"

[[bin]]
name = "abc465_c"
path = "abc465/c.rs"

[[bin]]
name = "abc465_d"
path = "abc465/d.rs"

[[bin]]
name = "abc465_e"
path = "abc465/e.rs"

[[bin]]
name = "abc465_f"
path = "abc465/f.rs"

[[bin]]
name = "abc466_a"
path = "abc466/a.rs"

[[bin]]
name = "abc466_b"
path = "abc466/b.rs"

[[bin]]
name = "abc466_c"
path = "abc466/c.rs"

[[bin]]
name = "abc466_d"
path = "abc466/d.rs"

[[bin]]
name = "abc466_e"
path = "abc466/e.rs"

[[bin]]
name = "abc466_f"
path = "abc466/f.rs"

[[bin]]
name = "abc467_a"
path = "abc467/a.rs"

[[bin]]
name = "abc467_b"
path = "abc467/b.rs"

[[bin]]
name = "abc467_c"
path = "abc467/c.rs"

[[bin]]
name = "abc467_d"
path = "abc467/d.rs"

[[bin]]
name = "abc468_a"
path = "abc468/a.rs"

[[bin]]
name = "abc468_b"
path = "abc468/b.rs"

[[bin]]
name = "abc468_c"
path = "abc468/c.rs"

[[bin]]
name = "abc468_d"
path = "abc468/d.rs"

[[bin]]
name = "abc468_e"
path = "abc468/e.rs"

[[bin]]
name = "abc468_f"
path = "abc468/f.rs"

[[bin]]
name = "abc469_a"
path = "abc469/a.rs"

[[bin]]
name = "abc469_b"
path = "abc469/b.rs"

[[bin]]
name = "abc469_c"
path = "abc469/c.rs"

[[bin]]
name = "abc469_d"
path = "abc469/d.rs"

[[bin]]
name = "abc469_e"
path = "abc469/e.rs"

[[bin]]
name = "abc470_a"
path = "abc470/a.rs"

[[bin]]
name = "abc470_b"
path = "abc470/b.rs"

[[bin]]
name = "abc470_c"
path = "abc470/c.rs"

[[bin]]
name = "abc470_d"
path = "abc470/d.rs"

[[bin]]
name = "abc470_e"
path = "abc470/e.rs"

[[bin]]
name = "abc471_a"
path = "abc471/a.rs"

[[bin]]
name = "abc471_b"
path = "abc471/b.rs"

[[bin]]
name = "abc471_c"
path = "abc471/c.rs"

[[bin]]
name = "abc471_d"
path = "abc471/d.rs"

[[bin]]
name = "abc471_e"
path = "abc471/e.rs"

[[bin]]
name = "abc472_a"
path = "abc472/a.rs"

[[bin]]
name = "abc472_b"
path = "abc472/b.rs"

[[bin]]
name = "abc472_c"
path = "abc472/c.rs"

[[bin]]
name = "abc472_d"
path = "abc472/d.rs"

[[bin]]
name = "abc472_e"
path = "abc472/e.rs"

[[bin]]
name = "abc473_a"
path = "abc473/a.rs"

[[bin]]
name = "abc473_b"
path = "abc473/b.rs"

[[bin]]
name = "abc473_c"
path = "abc473/c.rs"

[[bin]]
name = "abc473_d"
path = "abc473/d.rs"

[[bin]]
name = "abc473_e"
path = "abc473/e.rs"
